### ISSUE TITLE
Transforming a tab into a window gesture is broken

### ISSUE THREAD

**Issue by khevencolino** [Alex313031/Thorium-Win-AVX2#101]
**System Details**
 - OS: Windows 11 BUILD 22631.2271
 - Thorium Version 116.0.5845.169

**Problem**
When tring to pull a tab from the tittle bar to transform it into a new window the browser crash, it's possible to do this action properly by right clicking into the tab and selecting Turn the tab into a new Window option, but the gesture is broken.

**Comment by gz83** [comment]
Do you have the experimental feature flag turned on?

@khevencolino
