### ISSUE TITLE
Is there a possibility to add "Double click Close TAB" for Thorium?

### ISSUE THREAD

**Issue by SuXiChao1101** [Alex313031/Thorium-Win-AVX2#102]
Thorium is a very good browser, very smooth. Would you like to ask the developers if there are plans to add a "double click TAB to close this TAB" function to Thorium in the future? Personally, I think this function is very useful and can improve the fault tolerance rate of the closed TAB page.
Thank you Thorium for your contributions to Internet users!

**Comment by gz83** [comment]
Already have this feature, you can turn it on in chrome://flags

@SuXiChao1101

**Comment by SuXiChao1101** [comment]
> Already have this feature, you can turn it on in chrome://flags
> 
> @SuXiChao1101

Sorry I didn't notice the content in chrome://flags/, thanks a lot!
