### ISSUE TITLE
Thorium WinUpdater has bug

### ISSUE THREAD

**Issue by Malus-risus** [Alex313031/Thorium-Win-AVX2#103]
**System Details**
 - OS: [Windows 11]
 - Thorium Version [116.0.5845.169(AVX2)]

**Problem**
Version 117 of Thorium-Win-AVX2 has not been released yet, but I can receive the update using Thorium WinUpdater, which is strange.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/69906215/8c71d42e-99eb-4ab5-8402-e34f25700645)

**Additional Notes**
none

**Comment by hyperio546** [comment]
Also 118 just dropper rofl
