### ISSUE TITLE
Live captions do not work

### ISSUE THREAD

**Issue by endmarsfr** [Alex313031/Thorium-Win-AVX2#104]
**System Details**
 - OS: Windows 10 - 19045.3570
 - Thorium Version 117.0.5938.157 (Build officiel) (64 bits)

**Problem**
With Google Chrome, live captions work fine on an English video.
But there are no live captions in this version

![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/21008405/10e09147-97a7-476a-a78e-2eed20db0c34)

**Comment by gz83** [comment]
If I'm not mistaken, this feature is only available on Chrome

@endmarsfr

**Comment by endmarsfr** [comment]
This feature also seems to be available (sorry, my screenshot is in French):
![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/21008405/3303af08-4db7-4d07-a641-e1a7d0f6dc3b)


And as you can see in the first screenshot, the caption slider is also available in English:
![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/21008405/f1d4a9b3-f6ea-414a-b6b9-c4255f4fc012)

**Comment by gz83** [comment]
The entrance to the function exists, but the recognition model behind it is not available

@endmarsfr

**Comment by endmarsfr** [comment]
> The entrance to the function exists, but the recognition model behind it is not available 
> @endmarsfr


Isn't that the definition of an issue?
:)
Regards

**Comment by gz83** [comment]
We may try to get the recognition model to work on Thorium, but haven't found a way yet.

@endmarsfr

**Comment by hyperio546** [comment]
> > The entrance to the function exists, but the recognition model behind it is not available
> > @endmarsfr
> 
> Isn't that the definition of an issue? :) Regards

Nope. Maybe the access to recognition files is only with Google. Maybe there is a server sided issue. You cannot really blame the devs for this.
