### ISSUE TITLE
Password and stable version

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Win-AVX2#36]
I  tried to save my google password with Thorium but it doesn't work :(

i see google chrome use version of chromium104, may it would will be better if Throium Browser use the same engine of chromium used by chrome browser because it will be more stable , more tested and more patched security version, thank you !

**Comment by Alex313031** [comment]
@trimechee Thorium is actually more patched, and more security, because it is newer. But it is less stable and less tested also.

Are you using google sync?

**Comment by Alex313031** [comment]
@trimechee  hmmm this is strange. Are you saying that you sign in to i.e. gmail, and it doesnt save your password on the next browser launch?

**Comment by trimechee** [comment]
Yes, normally i disable saving passwords but i enabled password saving and i sing in google account but the password is not saved, maybe i should add it manually to  password manager

**Comment by CCCAUCHY** [comment]
I have the same problem, how to import the password? I have a password csv file.

**Comment by Alex313031** [comment]
@trimechee @CCCAUCHY there is a flag to enable this functionality in thorium and chromium > `chrome://flags/#password-import`

**Comment by trimechee** [comment]
Marvelous ! 💯
