### ISSUE TITLE
Updater, ipv6

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Win-AVX2#38]
Hello, it will be amazing to simplify things for beginners and people and for more speed, that when we click on "about", we see the Thorium Browser github page or changelog relaeses, , and it will be great when a new version is published, that Thorium displays a warning pop up message if there is a new version and presents the direct link to the Thorium github download page, thank you very much !

i tried some of the special flags introduced by ungoogled chromium but it seems it dosn't work with Thorium browser, for exemple i can't disable qr generator, and dsable ipv6 with SetIpv6ProbeFalse, side panel.....it will be good if we can disable ipv6, thank you ! and also captive portal please, thank you :)

https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md

**Comment by Alex313031** [comment]
@trimechee I can add a link in the about page. And I can add the ipv6 and qr generator patches. 

Thorium already has the captive portal patch.

**Comment by trimechee** [comment]
Great :) finally  disable  qr generator is not important because it's static and don't consume power and it may be useful to connect some android app, wifi password.....so it's a good idea to keep qr generator, however, many don't have ipv6 router and I have disabled ip assistant service and ipv6 in the network card settings so disabling ipv6 may speed up the connection maybe.....

**Comment by Alex313031** [comment]
@trimechee https://github.com/Alex313031/Thorium/releases/tag/M107.0.5280.0, has chrome://version show a link in "The Thorium Authors"

**Comment by trimechee** [comment]
Sensational ! Thanks a lot 💯

**Comment by trimechee** [comment]
@Alex313031 I see you said : " or writing a Windows ISO to a USB drive, one should use [Rufus](https://github.com/pbatard/rufus) (Site linked below)."

https://thorium.rocks/win7


thank you for Thorium for windows 7 ! i juste have a technical question about rufus please, rufus is famous and good bur surprisingly on the web site of ALT Linux which is a russian linux distro, alt linux says in the installation guide: "



Writing hybrid ISO images to boot media
It's not recommended to use UNetbootin, Rufus or UltraISO as these are too "smart" and actually cripple the resulting media to barely bootable or even unbootable state.

It is recommended to use the following utilities.

USB flash drives
Linux: SUSE Studio Imagewriter (imagewriter package) or direct dd use
Windows: Win32 Disk Imager, HDD Raw Copy Tool and the likes"


so if you want to install a light linux distro like antix linux on a usb  flash drive, you shouldn't use rufus? and if you want to install windows 7 or windows 10 on a usb  flash drive , you should not use rufus ? what do you think please ?

**Comment by trimechee** [comment]
Mr Pete has respond me, Rufus is really awesome fantastic ! so Thorium os is optimized for rufus ? https://github.com/pbatard/rufus/issues/2035#issuecomment-1238368579

**Comment by trimechee** [comment]
Hello, Does Thorium os compatible with linux app ?

**Comment by Alex313031** [comment]
@trimechee ThoriumOS can be flashed to a USB stick with rufus. In fact, I actually recommend doing so on windows.

ThoriumOS can run linux apps, provided that crostini is enabled/installed. See > https://support.google.com/chromebook/answer/9145439
