### ISSUE TITLE
is there a way to make thorium use less resources then Microsoft edge when using the exact same extensions and doing the same thing. 

### ISSUE THREAD

**Issue by Cxsmo-ai** [Alex313031/Thorium-Win-AVX2#79]
is there a way to make thorium use less resources then Microsoft edge when using the exact same extensions and doing the same thing.

**Comment by Pickymarker** [comment]
![image](https://user-images.githubusercontent.com/74084396/227917164-920b7b77-0f56-494c-9e2b-435e44e79a0e.png)

**Comment by gz83** [comment]
> ![image](https://user-images.githubusercontent.com/74084396/227917164-920b7b77-0f56-494c-9e2b-435e44e79a0e.png)

@Pickymarker 

Do you have control variables when making comparisons? For example, the number of tabs, the number of extensions, whether the webpage plays video/animation, etc.

**Comment by Pickymarker** [comment]
same number of tabs same extensions and same video playing on the tab at same position in video

**Comment by gz83** [comment]
> same number of tabs same extensions and same video playing on the tab at same position in video

@Pickymarker 

What is the result after turning off all the performance-related options in edge?
