### ISSUE TITLE
Problem with tab mute

### ISSUE THREAD

**Issue by imdylan0831** [Alex313031/Thorium-Win-AVX2#89]
**System Details**
 - OS: Windows 11
 - Thorium Version 113.0.5672.177 

**Problem**
When a tab is playing media and you accidentally click the violet icon which mutes/unmutes the tab while you are in another tab, you will not be able to unmute the tab, and thus you need to duplicate the tab and close the old one to undo the mute. (e.g. you are in discord and you want to switch into spotify to check which song is playing, but instead mutes the audio on that tab) 

**Screenshots**
<img width="228" alt="image" src="https://github.com/Alex313031/Thorium-AVX2/assets/91943470/8e5fdd24-a128-4fb1-bc8f-6686345b027b">

**Comment by gz83** [comment]
Does this problem exist on the same version of Chrome/Chromium?

@imdylan0831

**Comment by imdylan0831** [comment]
The quick mute/unmute tab feature does not exist in chrome I think, but it exists in edge. I do not remember something like this happening in edge though.

**Comment by Alex313031** [comment]
@imdylan0831 @gz83 This is strange!! I don't think this is a Thorium specific thing. Because all I did was enable the feature by default (which was behind a flag), and change the icon color. I did nothing that should be causing this. I am assuming you are using the AVX2 version.

Can you send a site that this is known to happen on, and then I can test in a Win 10 and Win 11 VM to see if I can reproduce.

**Comment by imdylan0831** [comment]
Yes I am using AVX2 version. It happens when listening to this radio website [https://thesoundofphonk.ru/](url) but it also happens on actually any tab that plays a media. I've tried it with a regular youtube video playing, muting the youtube tab while in another tab and it only works for the first click (the mute), but you cannot unmute the tab anymore as the button doesn't work.

I also accidentally found another quirk that is probably related to this issue. That is if I use the purple button to mute/unmute a tab while being in the tab (e.g. I am watching video from youtube), I cannot actually use the mute/unmute button again if I switch to another tab for some reason, and even if I go back to the tab playing media, the button will not work.
