### ISSUE TITLE
Pinned tabs still disappear

### ISSUE THREAD

**Issue by lemon07r** [Alex313031/Thorium-Win-AVX2#92]
[Pinned tabs becoming inaccessible #87
](https://github.com/Alex313031/Thorium-AVX2/issues/87)
Exact same issue as before. Was not fixed in 113. Also I was incorrect about disabling tab scrolling to fix it. Having it disabled doesn't do anything.

**Comment by gz83** [comment]
The double-click to close tabs patch may be removed later. Removing this patch should solve the problem you are experiencing.

@lemon07r

**Comment by Alex313031** [comment]
@lemon07r Does it still occur with the latest M116 version?

**Comment by pomodori92** [comment]
I tried many times to pin and unpin tabs and the tabs don't disappear, so I think this issue is solved.

**Comment by maxwowpow** [comment]
My 50cents: have lots of tabs and ~10 groups. 
After updating thorium (avx2/win/117) SOME (last) groups (collapsed and 1 expanded group) firstly was invisible.
After some seconds and opening a new tab / clicking other groups / tabs the expanded/last.

Ideas: ~1. some reindexing/rendering internally after updating.
