### ISSUE TITLE
Some "dangerous" things can not be download

### ISSUE THREAD

**Issue by CCCAUCHY** [Alex313031/Thorium-Win-AVX2#96]
**System Details**
 - OS:  Windows 10 22h2
 - Thorium [Version ](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M114.0.5735.134)

**Problem**
Some "dangerous" things can not be download. For example, some .bin file. These file can be download by Edge but even if  Edge must take at least 10s to show the download window to tell me the "danger".

**Screenshots**

**Additional Notes**

**Comment by gz83** [comment]
Please make sure that the file you need to download is indeed safe. Also, I've never had the Thorium browser block a file I needed to download

@CCCAUCHY

**Comment by PabloLN** [comment]
This cannot be considered a problem! It lacks information, the same thing I say that some .exe cannot be downloaded...
Please provide more details.
*I'm just a regular user*
![thorium_Vh61xwt7MT](https://github.com/Alex313031/Thorium-AVX2/assets/51299266/2b531877-e7e6-4f9e-a818-1280e520e01e)

**Comment by CCCAUCHY** [comment]
> Please make sure that the file you need to download is really safe. Also, Thorium Browser has never blocked me from downloading files.
> 
> @CCCAUCHY

try [this](https://packages.debian.org/sid/mipsel/samba/download)

**Comment by gz83** [comment]
Please provide the download address of the file you were unable to download

@CCCAUCHY

**Comment by CCCAUCHY** [comment]
> Please provide the download address of the file you were unable to download
> 
> @CCCAUCHY

everything on that page

**Comment by gz83** [comment]
Does this problem exist with version 113?

@CCCAUCHY

**Comment by CCCAUCHY** [comment]
> Does this problem exist with version 113?
> 
> @CCCAUCHY

YES

**Comment by gz83** [comment]
Close the browser and rename the existing user data folder, open the browser again and then go to the site with the problem and try to download the files

@CCCAUCHY

**Comment by CCCAUCHY** [comment]
> Close the browser and rename the existing user data folder, open the browser again and then go to the site with the problem and try to download the files
> 
> @CCCAUCHY

It's no need to rename the folder. I use THORIUM.BAT in [zip](https://github.com/Alex313031/Thorium-AVX2/releases/download/M113.0.5672.177/Thorium_AVX2_113.0.5672.177.zip) to run thorium stanalone and issue still.

**Comment by Alex313031** [comment]
@CCCAUCHY Can you send a link for an example file for me to test.

**Comment by CCCAUCHY** [comment]
> @CCCAUCHY Can you send a link for an example file for me to test.

http://http.us.debian.org/debian/pool/main/s/samba/samba_4.18.5+dfsg-2_mipsel.deb
http://ftp.us.debian.org/debian/pool/main/s/samba/samba_4.18.5+dfsg-2_mipsel.deb

**Comment by Alex313031** [comment]
@CCCAUCHY This is because it is http:// instead of https://

How to get around this is right click the link, select "copy link adress", then open a new tab, paste the address, and press Enter
