### ISSUE TITLE
How can I update the portable version of Thorium?

### ISSUE THREAD

**Issue by driftywinds** [Alex313031/Thorium-Win-AVX2#98]
Do I just download the latest release and paste it into the already existing folder? Or is there another method that is reccomended for the portable verison?

**Comment by Alex313031** [comment]
@driftywinds I would reccomend downloading new version, and then moving your user profile into it.

**Comment by driftywinds** [comment]
> @driftywinds I would reccomend downloading new version, and then moving your user profile into it.

so the "USER_DATA" folder is what I should paste into the new version right?

**Comment by gz83** [comment]
> > @driftywinds I would reccomend downloading new version, and then moving your user profile into it.
> 
> so the "USER_DATA" folder is what I should paste into the new version right?

Yes，you can try

@driftywinds

**Comment by ltguillaume** [comment]
@driftywinds I just forked my updater for LibreWolf to help out with Thorium. See https://codeberg.org/ltguillaume/thorium-winupdater

**Comment by Alex313031** [comment]
@ltguillaume COOL! Can I fork it and make it a submodule of the main repo?

**Comment by Alex313031** [comment]
@gz83 @midzer Look at this.

**Comment by gz83** [comment]
> @gz83 @midzer Look at this.

Nice, we should do some testing on them to make sure it works

**Comment by ltguillaume** [comment]
> Can I fork it and make it a submodule of the main repo?
Not necessarily against that, but I'm just curious what the benefits for Thorium or WinUpdater would be. Just a more official "flair" or is there more to it?

I'm just asking, because I've gotten the same question for LibreWolf WinUpdater (which is already included in official releases), but I still have to answer 😋

1. I will change a few search/replace actions with variables, make some code not necessary for Thorium conditional and some inline strings that were changed into global constants, so that the codebase is basically the same and more easily managed.
2. If there would be a way to distinguish which current build is installed, I can automate the download from the right repo (win/win7/avx2). Is there something in the .exe that can allow me to identify which build it is? If not, perhaps you could add a field called `Build` to the version info when compiling?
3. I now see that the Win7 repo has different builds, so I think currently it jusy picks whichever build is first in the release JSON, so that has to be adjusted.

**Comment by Alex313031** [comment]
@driftywinds I meant fork it, but make yours a submodule of the repo. I can make PR requests as needed, so they show up in the repo.

Can you put it on github, like the librewolf updater? 

And yeah I will look into 2. and 3.

About 4. This file has all the available commandline args.
https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/util/initial_preferences_constants.cc

Of particular use is `--do-not-create-taskbar-shortcut` and `--system-level`. System level installs it in program files and makes shortcuts for all users. Running without any arguments installs it in %appdata% and makes shortcuts for the current user.

What about a .json file that I put on the website. Like thorium.rock/win7/dist.json

Which could contain something like
```
{

**Comment by ltguillaume** [comment]
> @ltguillaume I meant fork it, but make yours a submodule of the repo. I can make PR requests as needed, so they show up in the repo.
> 
> Can you put it on github, like the librewolf updater?

Will do.

> And yeah I will look into 2. and 3.

Great!

> About 4. This file has all the available commandline args. https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/util/initial_preferences_constants.cc

> Of particular use is `--do-not-create-taskbar-shortcut` and `--system-level`. System level installs it in program files and makes shortcuts for all users. Running without any arguments installs it in %appdata% and makes shortcuts for the current user.

Ahah, so I'll need to take into account the possibility that it's installed in Program Files and would then need admin rights like LibreWolf, good to know.

> What about a .json file that I put on the website. Like thorium.rock/win7/dist.json
> 
> Which could contain something like
> 
> ```
> {
>   "version": "109.0.x.x.x",
>   "sse2": "https://download/path/to/latest/sse2/.exe",
>   "sse3": "https://download/path/to/latest/sse3/.exe",
>   "avx": "https://download/path/to/latest/avx/.exe",
>   "avx2": "https://download/path/to/latest/avx2/.exe"
> }
> ```

No, the thing I need to ascertain somehow is which version the user currently has installed. There should be no problem to get the right download URL via the GitHub API after that.

**Comment by Alex313031** [comment]
@ltguillaume Simply running thorium.exe or chrome.exe with `--version` will print the version to stdout.

**Comment by ltguillaume** [comment]
Sorry, I didn't mean the version number, but the build of the version (so AVX2/AVX/Win7AVX2/Win7AVX/Win7SSE3/Win7x86).

**Comment by Alex313031** [comment]
@ltguillaume OOF. It might be possible to edit the .rc file used in thorium.exe

But what about a simpler approach. Simply a file called `thor_ver` with a single line in it coressponding to the version

AVX2/AVX/Win7AVX2/Win7AVX/Win7SSE3/Win7x86

I could make a thor_ver for each version, which would be copied into the out/thorium when building, and then I just tell the mini_installer build.gn to include the file. That way, whatever the user has installed can always be checked simply by parsing the one and only line in that file.

**Comment by Alex313031** [comment]
@ltguillaume Wowzers! Worst I have had is a secondary PSU let out the magic smoke.

But see > https://github.com/ltguillaume/thorium-winupdater/issues/1
